# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|ruby_data_silo_example| "https://github.com/transcend-io/ruby-data-silo-example" }

gem "sinatra", ">=2.2.0"
gem "faraday", ">=2.3.0"
gem "jwt", ">=2.2.1"
gem "dotenv", ">=2.7.6"