name: ci
on: push

jobs:
  run-depcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn install --immutable
      - run: yarn depcheck

  run-pre-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100 # need the history to do a changed files check below (source, origin)
      - uses: actions/setup-python@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn install --immutable
      - uses: pre-commit/action@v2.0.2
        with:
          extra_args: --source ${{ github.event.pull_request.base.sha || 'HEAD~1' }} --origin ${{ github.event.pull_request.head.sha || 'HEAD' }}

  build-and-upload-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn install --immutable
      - name: Build the typescript code
        run: cd typescript && yarn && yarn build
      - uses: actions/upload-artifact@main
        with:
          name: build artifacts
          path: build/

  build-to-npm:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - run-depcheck
      - build-and-upload-artifacts
      - run-pre-commits
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Configure NPM authentication
        run: |
          yarn config set npmAlwaysAuth true
          yarn config set npmAuthToken ${{ secrets.NPM_TOKEN }}
      - name: Publish to yarn/npm
        run: yarn && cd typescript && yarn npm publish

  build-to-github-packages:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - run-depcheck
      - build-and-upload-artifacts
      - run-pre-commits
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn
      - name: Configure Github Packages authentication
        run: |
          yarn config set npmAlwaysAuth true
          yarn config set npmRegistryServer https://npm.pkg.github.com
          yarn config set npmPublishRegistry https://npm.pkg.github.com
          yarn config set npmAuthToken ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to Github packages
        run: cd typescript && yarn npm publish
